spring:
  datasource:
    url: jdbc:mysql://my-database.cbuom6aeon9v.ap-northeast-2.rds.amazonaws.com:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: tailorlink06
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul