version: 0.2
env:
  git-credential-helper: 'yes'
  variables:
    # docker 파라미터 정의
    ECS_CONTAINER_NAME: tailorlink-ecs
    IMAGE_REPO_NAME: tailorlink-ecr # aws ecr에 등록이 되어 있는 name
    IMAGE_TAG: latest
    AWS_DEFAULT_REGION: ap-northeast-2

phases:
  pre_build:
    commands:
      # Docker push를 할 ECR에 로그인 필요
      # https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/get-login-password.html
      # https://stackoverflow.com/questions/77488134/codebuild-error-exit-status-127-file-name-too-long
      - echo Installing jq...
      - yum install -y jq
      - echo Logging in to Amazon ECR...
      - aws --version
      - ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - echo -n ${ECR_PASSWORD} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      # 프로젝트 폴더로 이동
      - cd ./TailorLink_LLM
      - echo Building the Docker image...
      # Github Repository에 있는 Dockerfile의 위치에 맞춰 수정
      - docker build -f ./Dockerfile -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI

  post_build:
    commands:
      - echo Push the Docker image...
      - docker push $REPOSITORY_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $REPOSITORY_URI > ../imagedefinitions.json
      - echo Updating ECS Task Definition with Health Check...
      - aws ecs describe-task-definition --task-definition tailorLink-fastapi-task > current-task-definition.json
      - jq '.taskDefinition.containerDefinitions[0].healthCheck = {"command": [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ], "interval":
                                                                                                                                                   100, "timeout":
                                                                                                                                                     100, "retries":
                                                                                                                                                       3, "startPeriod": 60}' current-task-definition.json > task-definition-updated.json
      - aws ecs register-task-definition --cli-input-json file://task-definition-updated.json

  artifacts:
    files:
      - imagedefinitions.json
